---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-repo-two
  annotations:
    description: |
      Sample resource to identify a Git repository  
spec:
  type: git
  params:
    - name: url
      value: https://github.com/rmarting/strimzi-migration-demo.git
